#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tunarr"
name = "Tunarr"
description.en = "Create live TV channels from media"
description.fr = "Créer des chaînes de télévision en direct à partir de médias"

version = "1.0.4~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Zlib"
website = "https://tunarr.com/"
admindoc = "https://tunarr.com/"
code = "https://github.com/chrisbenincasa/tunarr"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "tunarr"
    extract = false
    amd64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.0.4/tunarr-1.0.4-linux-x64.tar.gz"
    amd64.sha256 = "5afa01d40e03250b38b8c7f1cd6b451843dc053fc06445f264e1e9a4d8534762"
    arm64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.0.4/tunarr-1.0.4-linux-arm64.tar.gz"
    arm64.sha256 = "090b357fc6e45f793196f27b66d22a3bebda00f0ad3f15b9b8e9583eed51c7d3"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\-linux-x64"
    autoupdate.asset.arm64 = ".*\\-linux-arm64"

    [resources.sources.ffmpeg]
    amd64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/7.1.1/ffmpeg-n7.1.1-56-gc2184b65d2-linux64-gpl-7.1.tar.xz"
    amd64.sha256 = "ffe261a2099629964231038dd4280ecc640b9cecc236253ee462d5a5232c3cac"
    arm64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/7.1.1/ffmpeg-n7.1.1-56-gc2184b65d2-linuxarm64-gpl-7.1.tar.xz"
    arm64.sha256 = "3c9858be9f06becc7f9c6088b19b8d6348c74dc23fe0df9113a54570d49de817"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg"
    