#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tunarr"
name = "Tunarr"
description.en = "Create live TV channels from media"
description.fr = "Créer des chaînes de télévision en direct à partir de médias"

version = "1.0.16~ynh1"

maintainers = ["eric_G"]

[upstream]
license = "Zlib"
website = "https://tunarr.com/"
admindoc = "https://tunarr.com/"
code = "https://github.com/chrisbenincasa/tunarr"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir = false
    rename = "tunarr"
    extract = false
    amd64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.0.16/tunarr-v1.0.16-linux-x64.tar.gz"
    amd64.sha256 = "5dfa4fcc4a912410c1626d558cf2f02bae3787b206f30c6e25d4205d49d3b3d5"
    arm64.url = "https://github.com/chrisbenincasa/tunarr/releases/download/v1.0.16/tunarr-v1.0.16-linux-arm64.tar.gz"
    arm64.sha256 = "5d65d0017123448619b01723b2478824de216b912de02fae9f723962fc055b62"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*\\-linux-x64"
    autoupdate.asset.arm64 = ".*\\-linux-arm64"

    [resources.sources.ffmpeg]
    amd64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/7.1.1/ffmpeg-n7.1.1-56-gc2184b65d2-linux64-gpl-7.1.tar.xz"
    amd64.sha256 = "ffe261a2099629964231038dd4280ecc640b9cecc236253ee462d5a5232c3cac"
    arm64.url = "https://github.com/ErsatzTV/ErsatzTV-ffmpeg/releases/download/7.1.1/ffmpeg-n7.1.1-56-gc2184b65d2-linuxarm64-gpl-7.1.tar.xz"
    arm64.sha256 = "3c9858be9f06becc7f9c6088b19b8d6348c74dc23fe0df9113a54570d49de817"

    [resources.system_user]

    [resources.install_dir]

    #[resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "ffmpeg"
    